### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Morriz** [swisskyrepo/BlockfolioTerminal#1]
I believe the api url does not work anymore...please contact the author of blockfolio to see if he can provide an alternative ;)

**Comment by swisskyrepo** [comment]
Hello,
I have checked, the API and the script are still working ;)

**Comment by Morriz** [comment]
Weird, I don’t get any data anymore...

**Comment by didyouexpectthat** [comment]
After adding my API key, I get this.
```
user@computer:~/src/BlockfolioTerminal$ python --version
Python 2.7.12
user@computer:~/src/BlockfolioTerminal$ ./blockfolio.py
Traceback (most recent call last):
  File "./blockfolio.py", line 134, in <module>
    print block
  File "./blockfolio.py", line 101, in __str__
    self.colorize(self.PORTFOLIO['changeFiat'])
  File "./blockfolio.py", line 73, in colorize
    string = str(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 3: ordinal not in range(128)
```
Without API key (default), I get this:
```
user@computer:~/src/BlockfolioTerminal$ ./blockfolio.py
+--------------------------+-------------+------------------+
| Portfolio value (Fiat $) | 24h chg (%) | 24h chg (Fiat $) |
+--------------------------+-------------+------------------+
|           $.0            |    +.00%    |       +$.0       |
+--------------------------+-------------+------------------+
+------+------------------------+----------+----------------+------------------+-------------+----------+
| Coin | Holding value (Fiat $) | Quantity | Price (Fiat $) | 24h chg (Fiat $) | 24h chg (%) | Chg/Week |
+------+------------------------+----------+----------------+------------------+-------------+----------+
+------+------------------------+----------+----------------+------------------+-------------+----------+
```

**Comment by Morriz** [comment]
I got a response from the blockfolio guys, and the correct url and format is like this:

http://api-v0.blockfolio.com/rest/get_all_positions/blockfolio?use_alias=true

**Comment by swisskyrepo** [comment]
Hi, 
Can you try again and tell me if it's fixed ?
Btw your new "url" doesn't seem to work :/
